[ModuleRSSI]
NAME=RSSI
PLUGIN_NAME=Tcl
ID=3
TIMEOUT=30

# Path in the file system where the analog voltage inputs can be monitored
ANALOG_GPIO_PATH="/sys/bus/iio/devices/iio:device0/in_voltage" 
# note that you may have to update the tcl file, as the final path is defined as
# "/sys/bus/iio/devices/iio:device0/in_voltage<number 0-N>_raw".  This supports the 
# MCP320x drivers under raspberry pi by default.

RSSI_ANALOG_INPUT_PIN=1
