; This is the module configuration file

[Module_Info]
mod_name = "RSSI"
version = "1.0"
min_orp_ver = "2.1.0"
authors = "Bob Iannucci, W6EI"
display_name = "RSSI"
mod_desc = "The RSSI module gives over-the-air signal reports in S-units.
</br></br>
This module has been designed specifically for the ICS-PI-REPEATER-1X/2X hardware platforms."